### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by User27636243** [Nyaacinth/Telekinesis#2]
!!tp homes就这样了

Traceback (most recent call last):
  File "/run/media/root/SSD/MCDR/plugins/Telekinesis.py", line 720, in on_user_info
    tp_homes(server,info)
  File "/run/media/root/SSD/MCDR/plugins/Telekinesis.py", line 600, in tp_homes
    homes = ' '.join(getHomes(server,info.player))
  File "/run/media/root/SSD/MCDR/plugins/Telekinesis.py", line 306, in getHomes
    player = getPlayerUUID(server,player)
  File "/run/media/root/SSD/MCDR/plugins/Telekinesis.py", line 243, in getPlayerUUID
    uuid_int_array = server.get_plugin_instance('minecraft_data_api').get_player_info(playername,'UUID')
  File "/run/media/root/SSD/MCDR/plugins/MinecraftDataAPI.py", line 245, in get_player_info
    return player_data_getter.get_player_info(player, data_path, timeout)
  File "/run/media/root/SSD/MCDR/plugins/MinecraftDataAPI.py", line 46, in get_player_info
    raise RuntimeError('Cannot invoke get_player_info on the task executor thread')
RuntimeError: Cannot invoke get_player_info on the task executor thread

**Comment by User27636243** [comment]
用的mcdr 1.5+centos7.9

**Comment by Nyaacinth** [comment]
已修复： [#1612d3](https://github.com/Nyaacinth/Telekinesis/commit/1612d3775068ae5ca884d3cd75dfa12ac238ddb5)

**Comment by Nyaacinth** [comment]
（手滑了）

**Comment by Nyaacinth** [comment]
本地测试看起来是没有问题了，您可以试试刚发的 release [v1.0.1](https://github.com/Nyaacinth/Telekinesis/releases/tag/1612d37)
如果没有问题了（或仍有问题）还请回复一下确认，多谢了

**Comment by User27636243** [comment]
\修好了好耶/
